<?php include INCLUDE_PATH .'/header.phtml'; ?>

<table class="table table-hover">
    <thead class="table-primary">
        <th>Sport</th>
    </thead>
<?php foreach ($data['sports'] as $sport): ?>
    <tbody>
        <tr>
            <td><?= $sport->sport; ?></td>
        </tr>
    </tbody>
<?php endforeach;?>
</table>

<form action="<?= URL_ROOT; ?>sports/submit" method="POST">

<div class="form-group">
                    <label for="sport" class="required font-weight-bold">sport</label>
                    <input type="sport" id="sport" class="form-control" name="sport" placeholder="sport" required="required"
                           value="<?= isset($_SESSION['form_data']['sport']) ? $_SESSION['form_data']['sport'] : ''; ?>">
                    <small class="text-danger"><?= isset($_SESSION['form_errors']['sport']) ? $_SESSION['form_errors']['sport'] : ''; ?></small>
                </div>
                <input class="btn btn-primary btn-block" type="submit" value="Add">
</form>

<?php include INCLUDE_PATH .'/footer.phtml'; ?>