<?php include INCLUDE_PATH .'/header.phtml'; ?>
<div class="row mt-5">
    <div class="col-md-4">
        <?php foreach($data['sports'] as $user): ?>
            <input class="form-control my-3" list="datalistOptions" id="exampleDataList" placeholder="Type to search">
            <datalist id="datalistOptions">
            <option value="<?= $user->sport; ?>">
        <?php endforeach;?>
            </datalist>
    </div>
    <div class="col-md-9">
        <table class="table table-hover table-sm">
            <thead class="table-primary">
                <th>#</th>
                <th>Sport</th>
            </thead>
        <?php foreach ($data['sports'] as $key => $sport): ?>
            <tbody>
                <tr>
                    <td><?= ++$key; ?></td>
                    <td><?= $sport->getSport(); ?></td>
                </tr>
            </tbody>
        <?php endforeach;?>
        </table>
    </div>
</div>
       


<?php include INCLUDE_PATH .'/footer.phtml'; ?>