<?php include_once INCLUDE_PATH .'header.phtml'; ?>
<div class="row mt-5">
    <div class="col-md">
        <div class="row mt-5">
            <div class="col-md">
       
                <hr>
            <?php foreach($data['users'] as $user):?>


                <table class="table table-hover">
                    <thead class="table-primary">
                        <th>Username</th>
                        <th>Email</th>
                        <th>Join date</th>
                        <th>Action</th>
                    </thead>
                        <tbody>
                        <tr>
                            <td><?= $user->username ?></td>
                            <td><?= $user->email ?></td>
                            <td><?= $user->joined ?></td>
                            <td><a class="btn btn-primary" href="user/edit">Action</a></td>
                        </tr>
                    </tbody>
                </table>
                <?php endforeach;?>
            </div>
        </div>
    </div>
</div>
<?php include_once INCLUDE_PATH . 'footer.phtml'; ?>


