<?php include_once INCLUDE_PATH .'header.phtml'; ?>

<div class="row mt-5">
    <div class="col-md">
        <div class="row ">
            <div class="col-md">
       
            <div class="card-group ">
                <?php foreach($data['users'] as $user): ?>
            <div class="card ">
                <img src="..." class="card-img-top" alt="avatar">
                <div class="card-body">
                    <h5 class="card-title"><?= $user->getUsername(); ?></h5>
                    <p class="card-text"><?= $user->getEmail(); ?></p>
                </div>
                <div class="card-footer">
                    <small class="text-muted"><?= $user->getJoined(); ?></small>
                </div>
            </div>
                    <?php endforeach;?>
            </div>
                <a class="btn btn-primary my-3" href="/SportEvents/user/edit/<?= $user->id; ?>">Edit</a>
            
            </div>
        </div>
    </div>
</div>
<?php include_once INCLUDE_PATH . 'footer.phtml'; ?>


