<?php include INCLUDE_PATH .'/header.phtml'; ?>
<!-- Register Modal -->
<?php include "register.phtml"; ?>
<!-- Login Modal -->
<?php include "login.phtml"; ?>


<div class="row mt-5">
    <div class="col-md">
        <!--SportEvents-->
    <?php foreach($data['users'] as $user):?>
        <?php endforeach;?>
       
        <table class="table table-hover">
                    <thead class="table-primary">
                        <th>Username</th>
                        <th>Email</th>
                        <th>Join date</th>
                        <th>Action</th>
                    </thead>
                        <tbody>
                        <tr>
                            <td><?= $user->username ?></td>
                            <td><?= $user->email ?></td>
                            <td><?= $user->joined ?></td>
                            <!-- TO DO -->
                            <td><a class="btn btn-primary" href="user/edit">Change Password</a></td>
                        </tr>
                    </tbody>
                </table>
    </div>
</div>
<?php include INCLUDE_PATH .'/footer.phtml'; ?>